name: Automation ğŸ›ï¸

on:
  workflow_call:
    secrets:
      JF_BOT_TOKEN:
        required: true

jobs:
  label:
    name: Label conflicted PRs ğŸ·ï¸â›”
    if: ${{ always() && !cancelled() }}
    runs-on: ubuntu-slim

    steps:
      - name: Check all PRs for merge conflicts and label them â›”
        uses: eps1lon/actions-label-merge-conflict@v3.0.3
        with:
          dirtyLabel: "merge conflict"
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
