name: Quality checks ðŸ‘ŒðŸ§ª

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '30 7 * * 6'
  workflow_dispatch:

jobs:
  dependency-review:
    name: Vulnerable dependencies ðŸ”Ž
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Scan
        uses: actions/dependency-review-action@v3.0.0

  lint:
    name: Lint ðŸ”¬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v3.1.0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ðŸ“¦
        run: npm ci --no-audit

      - name: Run linter âœï¸
        run: 'npm run lint:js && npm run lint:style'

  test:
    name: Test ðŸ§«
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ðŸ“¦
        run: npm ci --no-audit

      - name: Run tests ðŸ§ª
        run: npm run test

      - name: Upload coverage â¬†ï¸
        uses: codecov/codecov-action@v3.1.1

  build:
    name: Build frontend ðŸ› ï¸
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'linux/amd64'
          - 'linux/arm64'
          - 'linux/arm'

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v3.1.0

      - name: Configure QEMU âš™ï¸
        uses: docker/setup-qemu-action@v2.1.0

      - name: Configure Docker Buildx âš™ï¸
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build Docker images ðŸ› ï¸
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: |
            jellyfin/jellyfin-vue:pr-build

      - name: Extract built client and Docker image for artifact publishing ðŸ“¦
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          docker save jellyfin/jellyfin-vue:pr-build > docker_image.tar
          docker cp $(docker create --name jf jellyfin/jellyfin-vue:pr-build):/usr/share/nginx/html/ ./dist
          docker rm jf

      - name: Upload artifact (Docker image) â¬†ï¸ðŸ“¦
        uses: actions/upload-artifact@v3.1.1
        if: ${{ matrix.platform == 'linux/amd64' }}
        with:
          name: docker_image
          path: |
            docker_image.tar

      - name: Upload artifact (Client) â¬†ï¸ðŸ’»
        uses: actions/upload-artifact@v3.1.1
        if: ${{ matrix.platform == 'linux/amd64' }}
        with:
          name: frontend
          path: |
            dist

  tauri:
    name: Build Tauri ðŸ› ï¸
    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'macos-latest'
          - 'ubuntu-latest'
          - 'windows-latest'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v3.1.0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ðŸ“¦
        run: npm ci --no-audit -w tauri

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Generate Tauri icons ðŸ–Œï¸
        run: 'npm run tauri:icon -w tauri'

      - name: Build Tauri ðŸ› ï¸
        run: 'npm run tauri:build -w tauri'

      - name: Upload artifact (Linux) â¬†ï¸ðŸ§
        uses: actions/upload-artifact@v3.1.1
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: jellyfin-vue_linux-amd64
          path: |
            tauri/target/release/bundle/deb/*.deb
            tauri/target/release/bundle/appimage_deb

      - name: Upload artifact (MacOS) â¬†ï¸ðŸŽ
        uses: actions/upload-artifact@v3.1.1
        if: matrix.platform == 'macos-latest'
        with:
          name: jellyfin-vue_macOS
          path: |
            tauri/target/release/bundle/macos
            tauri/target/release/bundle/dmg/*.dmg

      - name: Upload artifact (Windows) â¬†ï¸ðŸªŸ
        uses: actions/upload-artifact@v3.1.1
        if: matrix.platform == 'windows-latest'
        with:
          name: jellyfin-vue_windows_amd64
          path: tauri/target/release/jellyfin-vue.exe

  pr_number:
    name: Save PR number as artifact
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > PR_number

      - name: Upload PR number as artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PR_number
          path: PR_number
