name: Deploy ğŸ—ï¸

on:
  workflow_run:
    workflows:
      - Quality Checks ğŸ‘ŒğŸ§ª
    types:
      - completed
  workflow_call:
    inputs:
      workflow_run_id:
        description: Run ID of the workflow whose artifacts are going to be downloaded
        required: true
        type: string
      branch:
        description: Name of the branch that it's being deployed
        required: true
        type: string

jobs:
  cf-pages:
    name: CloudFlare Pages ğŸ“ƒ
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow artifact â¬‡ï¸
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          run_id: ${{ inputs.workflow_run_id || github.event.workflow_run.id }}

      - name: Publish to Cloudflare Pages ğŸ“ƒ
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jf-vue
          directory: dist
          branch: ${{ inputs.branch || github.event.workflow_run.head_branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
