name: Deploy ğŸ—ï¸

on:
  workflow_run:
    workflows:
      # Deploy on pull requests
      - Quality checks ğŸ‘ŒğŸ§ª
      # Deploy on all releases
      - Release ğŸŒ
    types:
      - completed

jobs:
  cf-pages:
    name: CloudFlare Pages ğŸ“ƒ
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.cf.outputs.url }}

    steps:
      - name: Download workflow artifact â¬‡ï¸
        uses: actions/download-artifact@v4.1.7
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.JF_BOT_TOKEN }}
          name: frontend
          path: dist

      - name: Publish to Cloudflare Pages ğŸ“ƒ
        uses: cloudflare/pages-action@v1.5.0
        id: cf
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jf-vue
          directory: dist
          branch: ${{ github.event.workflow_run.head_branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  compose-comment:
    name: Compose comment ğŸ“
    if: ${{ always() }}
    uses: ./.github/workflows/job_messages.yml
    needs:
      - cf-pages

    with:
      branch: ${{ github.event.workflow_run.head_branch }}
      commit: ${{ github.event.workflow_run.head_commit.id }}
      preview_url: ${{ needs.cf-pages.outputs.url }}
      build_workflow_run_id: ${{ github.event.workflow_run.id }}
      commenting_workflow_run_id: ${{ github.run_id }}
      in_progress: false

  comment-status:
    name: Create comment status ğŸ“Š
    if: ${{ always() && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].number != '' }}
    runs-on: ubuntu-latest
    needs:
      - compose-comment

    steps:
      - name: Update job summary in PR comment ğŸ”ƒ
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.outputs.msg }}
          pr_number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment_tag: ${{ needs.compose-comment.outputs.marker }}
