name: Deploy ðŸ—ï¸

on:
  workflow_run:
    workflows:
      - Quality checks ðŸ‘ŒðŸ§ª
      - Unstable release ðŸª²ðŸ“¦
    types:
      - completed

jobs:
  cf-pages:
    name: CloudFlare Pages ðŸ“ƒ
    if: ${{ always() && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.cf.outputs.url }}

    steps:
      - name: Download workflow artifact â¬‡ï¸
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: frontend
          path: dist

      - name: Publish to Cloudflare Pages ðŸ“ƒ
        uses: cloudflare/pages-action@v1.1.0
        id: cf
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jf-vue
          directory: dist
          branch: ${{ github.event.workflow_run.head_branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  pr-context:
    name: Get PR context
    if: ${{ always() && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ env.pr_sha }}
      pr_number: ${{ env.pr_number }}

    steps:
      - name: Get PR context â¬‡ï¸
        uses: dawidd6/action-download-artifact@v2.24.2
        id: pr_context
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: PR_context

      - name: Set PR context environment variables
        if: ${{ steps.pr_context.conclusion == 'success' }}
        run: |
          echo "pr_number=$(cat PR_number)" >> $GITHUB_ENV
          echo "pr_sha=$(cat PR_sha)" >> $GITHUB_ENV

  compose-comment:
    name: Compose comment
    if: ${{ always() && github.event.workflow_run.event == 'pull_request' }}
    uses: ./.github/workflows/job_messages.yml
    needs:
      - cf-pages
      - pr-context
    with:
      branch: ${{ github.event.workflow_run.head_branch }}
      commit: ${{ needs.pr-context.commit != '' && needs.pr-context.commit || github.event.workflow_run.head_sha }}
      preview_url: ${{ needs.cf-pages.url }}
      build_workflow_run_id: ${{ github.event.workflow_run.id }}
      commenting_workflow_run_id: ${{ github.run_id }}
      in_progress: false

  comment-status:
    name: Create comment status
    if: ${{ always() && github.event.workflow_run.event == 'pull_request' && needs.pr-context.outputs.pr_number != '' }}
    runs-on: ubuntu-latest
    needs:
      - compose-comment
      - pr-context

    steps:
      - name: Update job summary in PR comment
        uses: thollander/actions-comment-pull-request@v1.5.0
        if: ${{ always() }}
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.outputs.msg }}
          pr_number: ${{ needs.pr-context.outputs.pr_number }}
          comment_includes: ${{ needs.compose-comment.outputs.marker }}
