name: Deploy ðŸ—ï¸

on:
  workflow_run:
    workflows:
      - Quality Checks ðŸ‘ŒðŸ§ª
    types:
      - completed
  workflow_call:
    inputs:
      workflow_run_id:
        description: Run ID of the workflow whose artifacts are going to be downloaded
        required: true
        type: string
      branch:
        description: Name of the branch that it's being deployed
        required: true
        type: string

jobs:
  cf-pages:
    name: CloudFlare Pages ðŸ“ƒ
    runs-on: ubuntu-latest
    if: ${{ (inputs.workflow_run_id && inputs.branch) || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download workflow artifact â¬‡ï¸
        uses: dawidd6/action-download-artifact@v2.24.2
        with:
          run_id: ${{ inputs.workflow_run_id || github.event.workflow_run.id }}
          name: frontend
          path: dist

      - name: Publish to Cloudflare Pages ðŸ“ƒ
        uses: cloudflare/pages-action@v1.1.0
        id: cf
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jf-vue
          directory: dist
          branch: ${{ inputs.branch || github.event.workflow_run.head_branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create job summary ðŸ“–
        run: |
          echo '# CloudFlare Pages deployment' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.cf.outputs.url }}' >> $GITHUB_STEP_SUMMARY
