name: 'Merge Conflicts'

on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository == 'jellyfin/jellyfin-vue'
    steps:
      - uses: mschilde/auto-label-merge-conflicts@v2
        with:
          CONFLICT_LABEL_NAME: 'merge conflict'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
