name: Pull Request ğŸ“¥

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.sha || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    paths-ignore:
      - '**/*.md'
  merge_group:

jobs:
  compose-comment:
    name: Compose PR comment
    if: ${{ always() && !cancelled() }}
    uses: ./.github/workflows/reusable/job_messages.yml
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      commenting_workflow_run_id: ${{ github.run_id }}
      in_progress: true

  push-comment:
    name: Push comment to PR ğŸ–¥ï¸
    if: ${{ always() && !cancelled() && needs.compose-comment.result == 'success' }}
    runs-on: ubuntu-latest
    needs:
      - compose-comment

    steps:
      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: ${{ needs.compose-comment.outputs.msg }}
          comment_tag: ${{ needs.compose-comment.outputs.marker }}

  project:
    name: Project board ğŸ“Š
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.JF_BOT_TOKEN }}

  label:
    name: Labeling ğŸ·ï¸
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Label PR depending on modified files
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.JF_BOT_TOKEN }}

  build:
    name: Build ğŸ—ï¸
    uses: ./.github/workflows/reusable/package.yml
    # Start build after the comment is created
    needs:
      - push-comment
    # Needed for attestation publication
    permissions:
      id-token: write
      attestations: write
    with:
      commit: ${{ github.event.pull_request.head.sha }}

  quality_checks:
    name: Quality checks ğŸ‘ŒğŸ§ª
    uses: ./.github/workflows/reusable/quality_checks.yml
    permissions: {}
    with:
      commit: ${{ github.event.pull_request.head.sha }}

  codeql:
    name: CodeQL ğŸ—ï¸
    uses: ./.github/workflows/reusable/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      commit: ${{ github.event.pull_request.head.sha }}

  deploy:
    name: Deploy ğŸš€
    uses: ./.github/workflows/reusable/deploy.yml
    needs:
      - build
    permissions:
      contents: read
      deployments: write
    secrets: inherit
    with:
      # If the PR is from the master branch of a fork, append the fork's name to the branch name
      branch: ${{ github.event.pull_request.head.repo.full_name != github.repository && github.event.pull_request.head.ref == 'master' && format('{0}/{1}', github.event.pull_request.head.repo.full_name, github.event.pull_request.head.ref) || github.event.pull_request.head.ref }}
      comment: true
      pr_number: ${{ github.event.pull_request.number }}
      commit: ${{ github.event.pull_request.head.sha }}
