name: Pull Request ğŸ“¥

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:

permissions:
  pull-requests: read

jobs:
  push-comment:
    name: Create comments âœï¸
    if: ${{ always() && !cancelled() && github.repository == 'jellyfin/jellyfin-vue' }}
    uses: ./.github/workflows/__job_messages.yml
    secrets: inherit
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      in_progress: true
      comment: true

  automation:
    name: Automation ğŸ›ï¸
    if: ${{ always() && !cancelled() && github.repository == 'jellyfin/jellyfin-vue' }}
    uses: ./.github/workflows/__automation.yml
    secrets: inherit

  semantic-commits:
    if: ${{ always() && !cancelled() && github.repository == 'jellyfin/jellyfin-vue' }}
    runs-on: ubuntu-slim
    name: Semantic Pull Request ğŸ“š
    steps:
      - name: Validate PR title ğŸ‘Œ
        uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  label:
    name: Labeling ğŸ·ï¸
    if: ${{ always() && !cancelled() && github.repository == 'jellyfin/jellyfin-vue'}}
    runs-on: ubuntu-slim

    steps:
      - name: Label depending on modified files
        uses: actions/labeler@v6.0.1
        with:
          sync-labels: true
          repo-token: ${{ secrets.JF_BOT_TOKEN }}
