name: Pull Request Checks ğŸ‘ŒğŸ§ª

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint ğŸ”¬
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v2.4.0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ğŸ“¦
        run: npm ci --no-audit

      - name: Run linter âœï¸
        run: npm run lint

  test:
    name: Test ğŸ§«
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ğŸ“¦
        run: npm ci --no-audit

      - name: Run tests ğŸ§ª
        run: npm run test

      - name: Upload coverage â¬†ï¸
        uses: codecov/codecov-action@v2.0.3

  ssr:
    name: Build SSR ğŸ–¥ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v2.4.0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ğŸ“¦
        run: npm ci --no-audit

      - name: Build ğŸ› ï¸
        run: 'NUXT_ENV_COMMIT=$GITHUB_SHA npm run build:ssr'

  static:
    name: Build static ğŸ’»
    runs-on: ubuntu-latest

    steps:
      - name: Checkout â¬‡ï¸
        uses: actions/checkout@v2.4.0

      - name: Setup node environment âš™ï¸
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          check-latest: true

      - name: Install dependencies ğŸ“¦
        run: npm ci --no-audit

      - name: Build ğŸ› ï¸
        run: NUXT_ENV_COMMIT=$GITHUB_SHA npm run build
